"""
Demand Forecasting Agent Node.

Official LangChain & LangGraph implementation:
- Uses `llm.bind_tools([calculate_demand_forecast_tool])`
- Invokes model with messages history
- Executes tool invocation and returns official AIMessage
"""

import json
from datetime import datetime
from typing import Any, Dict
from langchain_core.messages import AIMessage, SystemMessage, ToolMessage
from src.supply_chain.state import SupplyChainState
from src.supply_chain.tools.forecasting_tools import calculate_demand_forecast_tool
from src.supply_chain.prompts import DEMAND_AGENT_PROMPT
from src.supply_chain.agents.agent_factory import build_react_agent

def demand_forecasting_node(state: SupplyChainState) -> Dict[str, Any]:
    sku = state.get("sku", "SKU-MED-901")
    context = f"\n\nContext:\nTarget SKU: {sku}\nHistorical Consumption for reference: [120, 115, 130, 125, 140, 110, 135]"
    system_msg = SystemMessage(content=DEMAND_AGENT_PROMPT + context)
    
    agent = build_react_agent([calculate_demand_forecast_tool])
    result = agent.invoke({"messages": [system_msg] + state.get("messages", [])})
    
    forecast_data = {}
    for msg in result["messages"]:
        if isinstance(msg, ToolMessage) and msg.name == "calculate_demand_forecast_tool":
            try:
                forecast_data = json.loads(msg.content)
            except json.JSONDecodeError:
                pass

    log_entry = f"[{datetime.now().strftime('%H:%M:%S')}] 📈 DEMAND_AGENT: Evaluated {sku}."
    if forecast_data:
        log_entry += f" Surge: {forecast_data.get('surge_percentage', '0%')} | Total: {forecast_data.get('total_projected_demand', 0)} units."

    # Return only the new messages generated by the sub-graph (ignoring the history we passed in)
    new_messages = result["messages"][len(state.get("messages", [])) + 1:] 
    
    return {
        "demand_forecast": forecast_data,
        "current_step": "DEMAND_FORECAST_COMPLETED",
        "agent_logs": [log_entry],
        "messages": new_messages,
    }

